### ISSUE TITLE
【vue】模板中的条件渲染(v-if/v-else)

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/vue.js.2.0#13]
# 条件渲染
> 逻辑语句连续写多次即可,里面直接写js判断即可
```html
<p v-if="zfdyk > 0" class="blackblue u-zfdyk u-up">{{zfdyk}}</p><!--红-->
<p v-else-if="zfdyk == 0" class="u-zfdyk">{{zfdyk}}</p><!--黑-->
<p v-else="ok" class="blackblue u-zfdyk">{{zfdyk}}</p><!--蓝-->
```
```html
<h1 v-if="ok">Yes</h1>
```
## 模板集合(多个节点)

```html
<template v-if="ok">
  <h1>Title</h1>
  <p>Paragraph 1</p>
  <p>Paragraph 2</p>
</template>
```

## v-else指令
> v-else 元素必须紧跟在 v-if 元素或者 v-else-if的后面——否则它不能被识别。
```html
<div v-if="Math.random() > 0.5">
  Sorry
</div>
<div v-else>
  Not sorry
</div>
```
## v-else-if指令

> 与 v-else 相似,，v-else-if 必须跟在 v-if 或者 v-else-if之后。
```html
<div v-if="type === 'A'">
  A
</div>
<div v-else-if="type === 'B'">
  B
</div>
<div v-else-if="type === 'C'">
  C
</div>
<div v-else>
  Not A/B/C
</div>
```
##  使用 key 控制元素的可重用
> 由于vue会尽可能的去减少dom的repaint所以如果是可以替换属性完成的事情，便不会去重新生成节点，所以通过给元素添加不同的key值可以保证重新创建节点。
```html
<template v-if="loginType === 'username'">
  <label>Username</label>
  <input placeholder="Enter your username" key="username-input">
</template>
<template v-else>
  <label>Email</label>
  <input placeholder="Enter your email address" key="email-input">
</template>
```
## v-show
- v-show会增加display:none;
- v-show不支持\<template\>语法

**Comment by xhxno36** [comment]
使用 key 控制元素的可重用，给template里面的元素再包裹一层div，就不能复用了，楼主知道是为什么吗
`<template v-if="loginType === 'username'">
  <div><label>Username</label>
  <input placeholder="Enter your username"></div>
</template>
<template v-else>
  <div><label>Email</label>
  <input placeholder="Enter your email address"></div>
</template>`
